### ISSUE TITLE
Missing tsc-watch in dependencies

### ISSUE THREAD

**Issue by drmikecrowe** [hugazo/vue-firebase-template#2]

**Comment by hugazo** [comment]
tsc-watch is only declared in functions and has it's dependencies declared there

**Comment by drmikecrowe** [comment]
Ah, I see -- I needed to change into `functions/` and do the `yarn` there too.  I'm no novice, but it's a step I missed.  

Somehow, I was following your outline and couldn't get it running.  I realize now I had tried to run `yarn dev` prior to `cd functions; yarn`, which is worth pointing out.
